# Cosmos REST Faucet configuration

verbose          = "yes"
transactions_log = "transactions.csv"
request_timeout    = "86400"

[cosmos]
prefix         = "cosmos"
denomination   = "uatom"

[testnets]
    [testnets.theta-testnet-001]
    node_url = "http://sentry-01.theta-testnet.polypore.xyz:26657"
    chain_id = "theta-testnet-001"
    faucet_address = "cosmos1j7qzunvzx4cdqya80wvnrsmzyt9069d3gwhu5p"
    daily_cap = "400000000"
    amount_to_send = "1000"
    tx_fees = "500"

    [testnets.theta-devnet]
    node_url = "http://one.theta-devnet.polypore.xyz:26657"
    chain_id = "theta-devnet"
    faucet_address = "cosmos1j7qzunvzx4cdqya80wvnrsmzyt9069d3gwhu5p"
    block_explorer_tx = ""
    daily_cap = "50000000"
    amount_to_send = "1000"
    tx_fees = "500"

