# Cosmos REST Faucet configuration

gaia_home_folder = "~/.flash"
transactions_log = "transactions.csv"
request_timeout    = "86400"

[cosmos]
prefix         = "cosmos"
denomination   = "uflsh"

[testnets]
    [testnets.flash]
    node_url = ""
    chain_id = "flash"
    faucet_address = "cosmos1jqu3m3zuyerzlzp7kh3fa3lmuamtuwqjjxmynh"
    daily_cap = "10000000000"
    amount_to_send = "10000000"
    tx_fees = "500"